### ISSUE TITLE
Transfer Data Back to Client Machine (aka "restore")

### ISSUE THREAD

**Issue by EccentricKnight** [runt1me/stormcloud#53]
We need a mechanism to transfer data back to the client machine - ideally a user-selected version when multiple backup versions are available.

**Comment by runt1me** [comment]
An MVP version of this is complete, pending additional testing and API integration.

I scoped it down a little bit for the MVP. This version will not handle file sizes over 300MB (arbitrarily chosen threshold which should be memory-safe from the server's perspective), so I will open a new issue (not pre-release req) for handling large file sizes for restore. We will need to probably adopt a streaming approach again for this, but it's going to unfortunately be different than the previous streaming we have done, since we are only streaming the HTTP response, and not initiating the request ourselves to the client.

Also, there is a remote possibility that we could have the server mark a file as restored which was not successfully returned to the client if for some reason the client does not successfully receive the response (it would have just successfully sent the request, so this should be unlikely, but it's still possible). I am tolerant of this risk for the MVP but I will open an issue for a future requirement to have the client send a separate "restore complete" API call to the server once the file has been successfully restored. Then the server can have true assurance that the file transfer was successful.

**Comment by runt1me** [comment]
Polished off a number of small issues on the client and server tonight to get this polished off. It now works end-to-end, with a few caveats:

- Need to do API integration into the command center so the user actually has a mechanism to queue a file for restore. Currently I am testing by just hand jamming them into the db.
- The code will only currently work with data that is properly encrypted on the server using fernet. This should be the case for any clients that have backed up files recently, but we do have some old stale test data hanging out on the server which is not encrypted still. That data will not get properly encoded and will probably give 500 series responses.

**Comment by runt1me** [comment]
With basic API integration done, I now consider the MVP version of Restore complete.

Nice work @EccentricKnight @PaulThomasWI!
